# Generated by Django 5.0.4 on 2024-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producttable1',
            fields=[
                ('productid', models.AutoField(db_column='productID', primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='productName', max_length=50, null=True)),
                ('prdouctprice', models.IntegerField(blank=True, db_column='prdouctPrice', null=True)),
                ('productdesc', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProductDesc', max_length=150, null=True)),
                ('image_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ProductTable1',
                'managed': False,
            },
        ),
    ]
